### ISSUE TITLE
Consolidate validation into one command

### ISSUE THREAD

**Issue by itskarlsson** [Ericsson/ecchronos#104]
Currently there are a few intregation test that should be run before pushing. In the future there will even be checks for code quality and code style that one would want to run before pushing. I suggest we create a common profile for all of them so that the developer can simply run one command.

Example:
`mvn clean install -P all_validation`

**Comment by eperott** [comment]
There is already a bunch of profiles to get integration tests going. What would be different with this one?

IMO, we should do as much as possible in the ordinary Maven lifecycle. Profiles can be a neat way to say that docker based integration tests should be included (as that has some unusual docker dependencies on the build host).

**Comment by itskarlsson** [comment]
The difference would be that all the profiles are bundled into one. Instead of running 4 different commands, you run one command to make sure your code is ready to be pushed.
