### ISSUE TITLE
(On-demand) Repair scheduling tool

### ISSUE THREAD

**Issue by emolsson** [Ericsson/ecchronos#158]
Currently we are lacking the possibility to schedule repairs using a tool, rather than using pure REST requests.
It's also not possible to schedule repairs for all keyspaces or all tables within a keyspace.

Items to complete:
* Repair multiple tables in a single command (REST or tool based).
* Add a python tool for scheduling repairs.
* Make sure we use the correct configuration when repairing tables on-demand.

**Comment by etedpet** [comment]
Also add the possibility to specify that only the _primary replicas_ of the data should be repaired. 
Similar to `nodetool repair --partitioner-range` which is recommended for routine maintenance.

This way the on-demand repair can be triggered on all nodes (for repairing a table or the entire cluster on demand) without having to repair everything x 3 (given RF=3)
