### ISSUE TITLE
Rest documentation needs some improvement

### ISSUE THREAD

**Issue by itskarlsson** [Ericsson/ecchronos#162]
Update the rest documentation with all the functionality and add a section in the README for it.

**Comment by etedpet** [comment]
True, documentation is needed for on-demand repairs
`POST <host>/repair-management/v1/schedule/keyspaces/<keyspace>/tables/<table>`

**Comment by masokol** [comment]
Since #316 REST doc is auto-generated. What's left in this issue is to "add a section in the README for it."

**Comment by itskarlsson** [comment]
Section in README exists, so nothing left to do here.
