### ISSUE TITLE
Document how ecchronoslib should be installed

### ISSUE THREAD

**Issue by etedpet** [Ericsson/ecchronos#170]
Both `ecc-status` and `ecc-config` scripts are dependent on pylib/ecchronoslib.
If the library is not installed, it requires the scripts to be executed from the correct directory (since the lib is loaded from a path relative to the scripts).

For example when having a symlink (`/usr/bin/ecc-config`) to the `ecc-config` script it will fail like this (when _ecchronos_ lib is not installed):

```
> ecc-config
Traceback (most recent call last):
  File "/usr/bin/ecc-config", line 23, in <module>
    from ecchronoslib import rest, table_formatter
ModuleNotFoundError: No module named 'ecchronoslib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ecc-config", line 28, in <module>
    from ecchronoslib import rest, table_formatter
ModuleNotFoundError: No module named 'ecchronoslib'
```

**Comment by masokol** [comment]
This was fixed when ecctool was introduced.
