### ISSUE TITLE
On-demand repair jobs not started after Cassandra restart

### ISSUE THREAD

**Issue by etedpet** [Ericsson/ecchronos#172]
When a Cassandra nod is restarted, the following is printed in the ecChronos log:

> {"timestamp":"2021-01-29T10:27:11.824Z","severity":"warning","message":"Failed to check connection: java.net.ConnectException: Connection refused (Connection refused)"}
> {"timestamp":"2021-01-29T10:27:11.825Z","severity":"warning","message":"stopping"}
> {"timestamp":"2021-01-29T10:27:11.970Z","severity":"error","message":"Unable to update table sizes, future metrics might contain stale data"}

After that it is no longer possible to trigger an on-demand repair. 

Example with the (ks1.tb1 table):
```
$ curl -X POST http://localhost:8081/repair-management/v1/schedule/keyspaces/ks1/tables/tb1
{"keyspace":"ks1","table":"tb1","lastRepairedAtInMs":-1,"repairedRatio":0.0,"status":"IN_QUEUE","nextRepairInMs":-1,"id":"c72be6e6-f5d8-44df-8cf3-61180f44903c","recurring":false}
```

The request is accepted and a response with an Id is returned. But nothing is printed to the logs and the repair on ks1.tbt is not triggered.

The following status is shown:
```
$ ecc-status -k ks1
---------------------------------------------------------------------------------------------------------------------------------------------
| Id                                   | Keyspace | Table | Status    | Repaired(%) | Repaired at         | Next repair         | Recurring | 
---------------------------------------------------------------------------------------------------------------------------------------------
| c72be6e6-f5d8-44df-8cf3-61180f44903c | ks1      | tb1   | IN_QUEUE  | 0.00        | -                   | -                   | False     |   <--- "Triggered on-demand repair"
| 9750dc30-621b-11eb-ad6c-c189d374d30c | ks1      | tb1   | COMPLETED | 100.00      | 2021-01-23 10:20:21 | 2021-01-30 10:20:21 | True      | 
---------------------------------------------------------------------------------------------------------------------------------------------
```

But the job is stuck in `IN_QUEUE` and never starts.

**If** ecChronos is also restarted, then the on-demand repair fails (`ERROR`), BUT another repair can then be triggered!

```
$ curl -X POST http://localhost:8081/repair-management/v1/schedule/keyspaces/ks1/tables/tb1
{"keyspace":"ks1","table":"tb1","lastRepairedAtInMs":-1,"repairedRatio":0.0,"status":"IN_QUEUE","nextRepairInMs":-1,"id":"fd214fd9-bf4b-4d7f-b7a1-cc690668e4b1","recurring":false}
$ ecc-status -k ks1
---------------------------------------------------------------------------------------------------------------------------------------------
| Id                                   | Keyspace | Table | Status    | Repaired(%) | Repaired at         | Next repair         | Recurring | 
---------------------------------------------------------------------------------------------------------------------------------------------
| c72be6e6-f5d8-44df-8cf3-61180f44903c | ks1      | tb1   | ERROR     | 0.00        | -                   | -                   | False     | 
| fd214fd9-bf4b-4d7f-b7a1-cc690668e4b1 | ks1      | tb1   | IN_QUEUE  | 0.00        | -                   | -                   | False     |  <--- "New(est) on-demand repair"
| 9750dc30-621b-11eb-ad6c-c189d374d30c | ks1      | tb1   | COMPLETED | 100.00      | 2021-01-23 10:42:13 | 2021-01-30 10:42:13 | True      | 
---------------------------------------------------------------------------------------------------------------------------------------------
```

This job (`fd214fd9-bf4b-4d7f-b7a1-cc690668e4b1`) will be executed successfully.

From the log:

> {"timestamp":"2021-01-29T10:46:33.079Z","severity":"info","message":"Running scheduled task Repair job of ks1.tb1"}
> {"timestamp":"2021-01-29T10:46:33.080Z","severity":"info","message":"Table ks1.tb1 running repair job (replicas=..."}

But it should be possible to trigger a manual (on-demand) repair after Cassandra have been restarted, _without_ also having to restart ecChronos.

**Comment by etedpet** [comment]
Just adding some extra information.

This issue is also relevant for "normal" scheduled repair. With the same scenario as above (Cassandra restarted but not ecChronos), the repairs are not successful. The log says:

> No last repaired at found for ks1.tb1, iterating over all repair entries
> Token range (8516627431874455514,8605367647031678473] was not found in metadata
> Token range (4927272652060783097,5631161034343311210] was not found in metadata
> ... many more lines like that ...
> RepairedAt: (min=9223372036854775807,max=-9223372036854775808,isRepaired=false,isPartiallyRepaired=false), calculated from: []
> **Assuming the table ks1.tb1 is new**, next repair 2021-02-02 07:47:39
> Table ks1.tb1 switched to repair state (canRepair=false,lastRepaired=1612251939947,replicaRepairGroup=[]

So even though it is not a new table - ecChronos thinkt it is and sets the status to `COMPLETED` - even though nothing has been repaired!

```
$ ecc-status -k ks1
---------------------------------------------------------------------------------------------------------------------------------------------
| Id                                   | Keyspace | Table | Status    | Repaired(%) | Repaired at         | Next repair         | Recurring |
---------------------------------------------------------------------------------------------------------------------------------------------
| 9750dc30-621b-11eb-ad6c-c189d374d30c | ks1      | tb1   | COMPLETED | 0.00        | 2021-02-02 07:49:40 | 2021-02-02 07:51:40 | True      |
---------------------------------------------------------------------------------------------------------------------------------------------
```
Note - in the example above the ks1.tb1 table is scheduled to run repairs every second minute (for testing).

**Comment by etedpet** [comment]
Should also not that this issue have been found when running ecChronos and Cassandra on Kubernets! The Cassandra process and ecChronos process run in the same Pod but in 2 different containers.

A possible workaround for this issue is to use the **DNS-name** for the pod/service instead of **localhost** in the `connection.cql.host` configuration.

That solves this issue but will not work for us in other situations, where we need to run a repair but the DNS-name (service) is available. So it is no long-term solution.

**Comment by itskarlsson** [comment]
The issue here is that the Cassandra driver doesn't return a token map in certain scenarios.

If a node uses localhost as listen address but has a different broadcast address, the node will start ecchronos with localhost. However, during a restart of cassandra, the driver switches out the localhost address with the broadcast address(because the control connection goes down and gets the active nodes from another node)

If this occurs, we still try to fetch tokens with localhost but receive an empty token list as localhost has been replaced by the broadcast address of the host.
