### ISSUE TITLE
Possiblity to disable all scheduling with configuration

### ISSUE THREAD

**Issue by simonfontana** [Ericsson/ecchronos#174]
We are planning to replace all repair handling (such as troubleshooting guidelines) with ecChronos in our solution. This means our deployment should have ecChronos enabled by default. However, some of our users may not want to use ecChronos for automatic repairs just yet as they may have other solutions in place. That's why we'd like a possibility to disable ecChronos automatic repair while still having the possibility to trigger on-demand repairs. I know it's possible to enable/disable scheduling per table, but it would be nice if we can have a similar configuration parameter on top-level.

I propose the introduction of a new parameter in ecc.yml:

```
## Repair configuration
## This section defines default repair behavior for all tables.
##
repair:
  ## If automatic repair should be enabled for all tables.
  ## Can be overridden by per-table configuration.
  enabled: true
```

**Comment by itskarlsson** [comment]
Already supported by setting repair interval to 0.
`  ##
  ## How often repairs should be triggered for tables.
  ##
  interval:
    time: 0
    unit: days`
