### ISSUE TITLE
Support multiple Cassandra version

### ISSUE THREAD

**Issue by emolsson** [Ericsson/ecchronos#20]
Currently ecChronos is verified to work with Apache Cassandra 3.0.x versions. It it known to not work with 2.2.x due to [this line](https://github.com/Ericsson/ecchronos/blob/master/core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/repair/RepairTask.java#L60).

Intended goal of this issue is to:
* Verify behavior with 3.x and 4.0 versions.
* Identify the changes needed to support multiple versions.
* Add separate builds if necessary to run tests towards different versions.

**Comment by masokol** [comment]
Closed with #270
