### ISSUE TITLE
Vulnerable 3PP - Jackson-databind

### ISSUE THREAD

**Issue by dapc11** [Ericsson/ecchronos#248]
The following [Jackson issue](https://github.com/FasterXML/jackson-databind/issues/3328) is describing a vulnerability in the current Jackson version in EcChronos.

Details from X-Ray:

XRAY-191477 
Severity 
- High

CVSS Score: 
- 7.1 (v2)
- 7.5 (v3)

Component: com.fasterxml.jackson.core:jackson-databind
Fix version: 2.12.6, 2.13.1, 2.14.0

**Comment by cowtowncoder** [comment]
Jackson releases 2.12.6 and 2.13.1 are now out, including the fix.
Issue mentioned has also been updated to describe actual vulnerability, to help developers gauge if there is any chance it actually is applicable to their use case -- in the vast majority of cases it is not.

**Comment by itskarlsson** [comment]
@cowtowncoder Great explanation in the issue. Very clear and concise.

@dapc11 We only use ObjectMapper to serialize and deserialize yaml files with jackson which means it isn't affecting ecChronos.
