### ISSUE TITLE
Documented size targets are incorrect

### ISSUE THREAD

**Issue by emolsson** [Ericsson/ecchronos#272]
The documented size targets are incorrect:
https://github.com/Ericsson/ecchronos/blob/fc29d669ae34799b016d533506ebbbc8e93c6483/application/src/main/resources/ecc.yml#L137

```
  ## 12  (12 B)
  ## 12k (1 KiB)
  ## 12m (1 MiB)
  ## 12g (1 GiB)
```

Should be:

```
  ## 12  (12 B)
  ## 12k (12 KiB)
  ## 12m (12 MiB)
  ## 12g (12 GiB)
```

**Comment by fraserc182** [comment]
Hi, I've submitted #274 to close this!
