### ISSUE TITLE
Support for Materialized Views

### ISSUE THREAD

**Issue by emolsson** [Ericsson/ecchronos#280]
Repairs are currently not performed on Materialized Views.

I haven't checked much details around other aspects (like metrics, etc) but it might be as simple as adding an additional call to `TableMetadata.getViews()` in the [ReplicatedTableProvider](https://github.com/Ericsson/ecchronos/blob/0d4f194e8c02ea38d259376ff252ae70300bc8d6/core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/utils/ReplicatedTableProviderImpl.java#L56) and then implementing an alternative to [TableReferenceFactory#forTable](https://github.com/Ericsson/ecchronos/blob/0d4f194e8c02ea38d259376ff252ae70300bc8d6/core/src/main/java/com/ericsson/bss/cassandra/ecchronos/core/utils/TableReferenceFactoryImpl.java#L39) for views.

Since both tables and views are backed by ColumnFamilyStores in Cassandra this might just work out of the box with metrics and everything else, but more investigation would be necessary during development.

Additionally it should be considered if this should be a feature that needs to be enabled or "always on".

**Comment by masokol** [comment]
Hi, I'm not sure if we want to support this in ecChronos.

In cassandra 3.X versions materialized views are marked as experimental and user gets a  warning during creation of materialized view.

In cassandra 4.0, materialized views are disabled by default and marked as experimental, a user needs to explicitly enable materialized views in cassandra.yaml

**Comment by jwaeab** [comment]
As already stated, this feature is still an experimental one and there are still open issues regarding materialized views (regarding repairs for them among other things).
