### ISSUE TITLE
Contribution guide could use some updates

### ISSUE THREAD

**Issue by masokol** [Ericsson/ecchronos#344]
Contribution guide needs some updates:
* Changelog entry should be at the top, not the bottom
* How the changelog entry should look like
* We should describe that there should be an issue for pull requests which are not very small (like fixing a typo)

**Comment by itskarlsson** [comment]
Additionally:

- All the chapters explaining how to run test cases should be broken out into a different .md file and linked to from the contributing.md file.
- Change ' i.e. Fixes #20.' to ' i.e. Closes #20.'
