### ISSUE TITLE
Log4J version in ecChronos 3.0.0

### ISSUE THREAD

**Issue by ArcturusMengsk** [Ericsson/ecchronos#356]
I believe that at one point, Log4J version in pom.xml was overridden with 2.15.0, to mitigate the Log4J issue that was so popular in December last year (2021). Back then, Spring Boot had a lower version of Log4J than 2.15.0, which was vulnerable, so the override made sense:
https://github.com/Ericsson/ecchronos/commit/528e2f0b8a144956bfef3087c90ce28120a44597

However, Spring Boot 2.6.6, the latest version used in ecChronos now has at least Log4J 2.17.2 by default, so this override should not be needed, and can simply be removed. I believe this was actually attempted later, but was only half-completed:
https://github.com/Ericsson/ecchronos/commit/1ab8bd5516354ca41ab4d06693c4e649a22fad78

If you compare the 2 patches, more stuff was added in the first than was removed in the second.

**Comment by itskarlsson** [comment]
Good catch!
