### ISSUE TITLE
RepairInfo sort functions

### ISSUE THREAD

**Issue by itskarlsson** [Ericsson/ecchronos#358]
It would be good to be able to sort the table based on Repair Time Taken and/or Repaired (%). It can get quite difficult to read with many tables in the same keyspace.

> | Keyspace  | Table                   | Repaired (%) | Repair time taken | 
> | repair    | rep151                  | 0.00         | -                 | 
> | repair    | rep152                  | 0.00         | -                 | 
> | repair    | rep153                  | 0.00         | -                 | 
> | repair    | rep154                  | 0.00         | -                 | 
> | repair    | rep155                  | 0.00         | -                 | 
> | repair    | rep156                  | 0.00         | -                 | 
> | repair    | rep157                  | 100.00       | 7 seconds         | 
> | repair    | rep158                  | 100.00       | 6 seconds         | 
> | repair    | rep159                  | 100.00       | 7 seconds         | 
> | repair    | rep16                   | 100.00       | 6 seconds         | 
> | repair    | rep160                  | 100.00       | 7 seconds         | 
> | repair    | rep161                  | 100.00       | 7 seconds         | 
> | repair    | rep162                  | 100.00       | 6 seconds         | 
> | repair    | rep163                  | 100.00       | 6 seconds         | 
> | repair    | rep164                  | 100.00       | 7 seconds         | 
> | repair    | rep165                  | 100.00       | 7 seconds         | 
> | repair    | rep166                  | 100.00       | 8 seconds         | 
> | repair    | rep167                  | 0.00         | -                 | 
> | repair    | rep168                  | 0.00         | -                 | 
> | repair    | rep169                  | 0.00         | -                 | 
> | repair    | rep17                   | 0.00         | -                 | 
> | repair    | rep170                  | 0.00         | -                 | 
> | repair    | rep171                  | 0.00         | -                 | 
> | repair    | rep172                  | 0.00         | -                 | 
> | repair    | rep173                  | 0.00         | -                 | 
> | repair    | rep174                  | 0.00         | -                 | 
> | repair    | rep175                  | 0.00         | -                 | 
> | repair    | rep176                  | 0.00         | -                 | 
> | repair    | rep177                  | 0.00         | -                 | 
> | repair    | rep178                  | 0.00         | -                 |

**Comment by masokol** [comment]
I would say that the sorting should work in the same way as for repairs and schedules.

**Comment by itskarlsson** [comment]
Agreed. Sorting by repaired % like the other tools would do the trick.
