### ISSUE TITLE
Metric status logger for troubleshooting

### ISSUE THREAD

**Issue by itskarlsson** [Ericsson/ecchronos#397]
During #394 there was an idea of a metrics logger that writes to debug when a threshold of failed requests is reached and gives a list of metrics for troubleshooting. The threshold would be able to be configured in the ecc.yml.

One would also have to change the behavior introduced in #394. When statistics is enabled but not reported, the statistics might write to log but not export it elsewhere instead of being complete disabled.

**Comment by manmagic3** [comment]
@itskarlsson @masokol can you please elaborate when you say " **threshold of failed requests is reached and gives a list of metrics for troubleshooting**".

**Comment by manmagic3** [comment]
The code is merged with https://github.com/Ericsson/ecchronos/pull/662. Closing this issue
