### ISSUE TITLE
Failed to initialize ecc post installation in VM (Cassandra 4.0.7 in Ubuntu)

### ISSUE THREAD

**Issue by cssndrthrift** [Ericsson/ecchronos#456]
Failed to initialize ecc post installation in VM (Cassandra 4.0.7 in Ubuntu)
Is this because of VM/there is nothing to repair/something else

ERROR c.e.b.c.e.a.spring.SpringBooter - Failed to initialize
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'ECChronos' defined in URL [jar:file:/home/somrajob/opt/software/ecchronos-binary-4.0.2/lib/application-4.0.2.jar!/com/ericsson/bss/cassandra/ecchronos/application/spring/ECChronos.class]: Unsatisfied dependency expressed through constructor parameter 7; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'repairHistoryBean' defined in URL [jar:file:/home/somrajob/opt/software/ecchronos-binary-4.0.2/lib/application-4.0.2.jar!/com/ericsson/bss/cassandra/ecchronos/application/spring/RepairHistoryBean.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ericsson.bss.cassandra.ecchronos.application.spring.RepairHistoryBean$$EnhancerBySpringCGLIB$$b973148]: Constructor threw exception; nested exception is com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: table repair_history does not exist

**Comment by masokol** [comment]
Hi,

it looks like the table repair_history does not exist, the table should be created prior to starting ecChronos:

```
CREATE TABLE IF NOT EXISTS ecchronos.repair_history(table_id uuid, node_id uuid, repair_id timeuuid, job_id uuid, coordinator_id uuid, range_begin text, range_end text, participants set<uuid>, status text, started_at timestamp, finished_at timestamp, PRIMARY KEY((table_id,node_id), repair_id)) WITH compaction = {'class': 'TimeWindowCompactionStrategy'} AND default_time_to_live = 2592000 AND CLUSTERING ORDER BY (repair_id DESC);
```

Also i noticed that this table is not documented in [https://github.com/Ericsson/ecchronos/blob/master/docs/SETUP.md#preparation](SETUP.md) so if you're up to it you can make a contribution.

**Comment by cssndrthrift** [comment]
Thanks.
Process started successfully and running

somrajob@somrajob-VirtualBox:~/opt/software/ecchronos-binary-4.0.2/bin$ ls -lrt
total 24
-rwxr-xr-x 1 somrajob somrajob 19854 Dec 15 19:47 ecctool
-rwxr-xr-x 1 somrajob somrajob  1742 Dec 15 19:47 ecc
somrajob@somrajob-VirtualBox:~/opt/software/ecchronos-binary-4.0.2/bin$ ./ecctool start
ecc started with pid 60446
somrajob@somrajob-VirtualBox:~/opt/software/ecchronos-binary-4.0.2$ ps -ef | grep -i 60446
somrajob   60446    1405 18 16:38 pts/2    00:00:16 java -Decchronos.config=/home/somrajob/opt/software/ecchronos-binary-4.0.2/bin/../conf -cp /home/somrajob/opt/software/ecchronos-binary-4.0.2/bin/../conf:/home/somrajob/opt/software/ecchronos-binary-4.0.2/bin/../lib/swagger-core-2.2.0.jar:/home/somrajob/opt/software/ecchronos-binary-4.0.2/bin/../lib/spring-boot-starter-logging-2.7.5.jar:/home/somrajob/opt/software/ecchronos-binary-4.0.2/bin/../lib/spring-boot-starter-actuator-2.7.5.jar:/home/somrajob/opt/software/ecchronos-binary-4.0.2/bin/../lib/spring-expression-5.3.23.jar:/home/somrajob/opt/software/ecchronos-binary-4.0.2/bin/../lib/micrometer-core-1.9.2.jar:/home/somrajob/opt/software/ecchronos-binary-4.0.2/bin/../lib/spring-boot-autoconfigure-2.7.5.jar:/home/somrajob/opt/software/ecchronos-binary-4.0.2/bin/../lib/reactive-streams-1.0.4.ja

**Comment by cssndrthrift** [comment]
I have proposed the change in SETUP.md. Kindly approve

**Comment by cssndrthrift** [comment]
Hello,

I have proposed the change as it resolved the issue.
I am also an Ericsson employee so I will test further and let you know for
any more bug.

I am doing all these in Ubuntu VM in my laptop,but if you have some
standard test server and you can give me access,it would be great.

Regards
Somraj

**Comment by masokol** [comment]
> I have proposed the change in SETUP.md. Kindly approve

You will have to create a pull request, also please read [CONTRIBUTING](https://github.com/Ericsson/ecchronos/blob/master/docs/CONTRIBUTING.md)
