### ISSUE TITLE
Support for RandomPartitioner?

### ISSUE THREAD

**Issue by kngatineau** [Ericsson/ecchronos#468]
While I was able to setup `ecChronos` v. `4.0.2` as a service just fine on a node running `Cassandra 3.11.14`, both manual and scheduled repairs fail.

Log message:
```21:01:35.046 [pool-5-thread-1] ERROR c.e.b.c.e.c.r.RepairSchedulerImpl - Unexpected error during schedule change of betable_payments_v2.schema_migrations:
java.lang.ClassCastException: com.datastax.oss.driver.internal.core.metadata.token.RandomToken cannot be cast to com.datastax.oss.driver.internal.core.metadata.token.Murmur3Token 
```

This is because the Cassandra cluster I am trying to set up `ecChronos` repairs with is configured using the  `RandomPartitioner` partition (it was configured prior to the `Murmur3Partition` became the default in Cassandra 1.2). Unfortunately, changing the partitioner for these nodes is not an option. 

If I may ask, what would need to be done to add compatibility for `RandomPartitioner`?

**Comment by masokol** [comment]
Hi,

I've done a quick investigation regarding this. Currently ecChronos assumes Murmur3Partition throughout the code (calculating ranges, splitting ranges, persisting repair history etc.).
Adding support for RandomPartitioner would require quite a lot of effort.
