### ISSUE TITLE
Make lock refresh + failure cache configurable

### ISSUE THREAD

**Issue by masokol** [Ericsson/ecchronos#543]
Make lock refresh and lock failure cache configurable, the defaults should be as they're today, but preferably dynamic based on the TTL of ecchronos.lock table.

Today these values are hardcoded (assuming TTL of 10 minutes):
* Lock refresh 1 min (retry 9 times)
* Lock failure cache, 30 secs

**Comment by SajidRiaz138** [comment]
I want to do this..
