### ISSUE TITLE
Make priority granularity configurable

### ISSUE THREAD

**Issue by masokol** [Ericsson/ecchronos#599]
I think it would be good if the priority granularity could be configurable. ecChronos calculates priority based on amount of hours that have passed since the repair "could" run. What this effectively means is that all schedules executed the same hour will have the same priority, i.e having repair interval less than 1 hour will produce strange results.

What i propose is to expose the granularity as a global setting in ecc.yml, something like:

```
repair:
  priority:
    granularity_unit: HOURS
```

The possible values for granularity_unit should be HOURS, MINUTES or SECONDS. HOURS should be default to not break upgrade from older versions of ecChronos. Also it should be mentioned as a comment in the config file that repair must be paused when changing the granularity. Additionally the priority calculation should be looked over to make sure we cap priority (overflow protection).

**Comment by SajidRiaz138** [comment]
Please assign this to me
