### ISSUE TITLE
Investigate Java 17

### ISSUE THREAD

**Issue by masokol** [Ericsson/ecchronos#607]
Investigate if ecChronos is working with java 17. If it doesn't then create issues for all work that needs to be done in order to be able to run with java 17.

**Comment by VictorCavichioli** [comment]
I will take this

**Comment by VictorCavichioli** [comment]
The investigation and implementation was done in PR [Build ecChronos With Java 17 - Issue #607](https://github.com/Ericsson/ecchronos/pull/617) but we have decided to wait to merge until develop a plan with major features that depends of Java 17.
