### ISSUE TITLE
Improve ecc.yml Documentation

### ISSUE THREAD

**Issue by ArcturusMengsk** [Ericsson/ecchronos#627]
Hello there,

The [ecc.yml](https://github.com/Ericsson/ecchronos/blob/master/application/src/main/resources/ecc.yml) file contains quite a lot of documentation, but the file itself is a bit hidden in the src code.

Is there a possibility to perhaps auto-generate an .md file from the ecc.yml file, and put it in the docs/ folder? I think that would be easier to read and understand.

**Comment by masokol** [comment]
Reopen requested by issuer.

**Comment by jwaeab** [comment]
"not quite what I had in mind" is not a good enough reason to reopen this. Create a new issue with a proper description if still valid.
