### ISSUE TITLE
[Robustness] Containerized ecchronos restarting tomcat when Cassandra peer is overloaded

### ISSUE THREAD

**Issue by joaofso** [Ericsson/ecchronos#650]
Story Description:

1. Setup
* CIL Datacenter with 28 pods
* Traffic simulator producing enough traffic "on the verge"of overload, so that if one pod is down, the system starts to reject requests due to ECOP inbound

2. Step
* Provoke a complete restart of the datacenter with the following command:
kubectl get pod | grep rack | awk '{ print $1 }' | xargs kubectl delete pod

3. Expected Result
* I expect that the Tomcat server that is running ecchronos does not get killed, restarting the ecchronos container.
* I expect that while the pods are starting up and the cassandra container from the pods are starting up and getting overloaded, this does not make ecchronos to get killed.
* In the end, I expect that the pods are able to get up and not be locked at startup

Acceptance Criteria:

* Ecchronos does not stop/break when cassandra is overloaded
* The target DC doesn't get stuck in a complete restart

Definition of Done:

Repeating the same test case from the "Story Description" and the ecchronos containers do not restart during the attempts

Log Excerpt:

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.ericsson.bss.cassandra.ecchronos.application.spring.RepairHistoryBean$$EnhancerBySpringCGLIB$$ed24782f]: Constructor threw exception; nested exception is com.datastax.oss.driver.api.core.DriverTimeoutException: Query timed out after PT2S

{"version":"1.0.0","timestamp":"2024-03-19T14:35:57.949Z","severity":"warning","service_id":"eric-bss-cil-database-cd","message":"[main] [org.springframework.beans.factory.support.DisposableBeanAdapter] Invocation of close method failed on bean with name 'defaultRepairConfigurationProvider': java.lang.NullPointerException"}
{"version":"1.0.0","timestamp":"2024-03-19T14:35:57.952Z","severity":"info","service_id":"eric-bss-cil-database-cd","message":"[main] [org.apache.catalina.core.StandardService] Stopping service [Tomcat]"}

**Comment by VictorCavichioli** [comment]
Hi @joaofso, we actually have a retry policy in the connection provider, ecchronos will retry to connect to cassandra until the timeout finish, this value by default is 0, which means that if a connection fails in the first try, it will break, but you can change this timeout as you need through ecc.yml, check this: https://github.com/Ericsson/ecchronos/blob/master/application/src/main/resources/ecc.yml#L34
