### ISSUE TITLE
Is it possible to change configuration dynamically?

### ISSUE THREAD

**Issue by smiklosovic** [Ericsson/ecchronos#74]
Hi,

maybe it is obvious but I am sorry I have not had a chance to read the code in depth.

Is there any way how to set some configuration properties after I start the binary? I am not completely sure what property that would be, I am more interested about general possibility to do that. If something is running for a very long time, I do not want to touch that and restart it manually just to configure it differently. Maybe something based on JMX would help here?

**Comment by emolsson** [comment]
My apologies for taking this long to respond here.

Currently this is only possible when running in an OSGi environment but the way it's done there is basically a restart of the affected components.

In the standalone application mode the [setup](https://github.com/Ericsson/ecchronos/blob/master/application/src/main/java/com/ericsson/bss/cassandra/ecchronos/application/ECChronos.java) is currently a bit complicated and it would be hard to implement something similar in an easy way. The main challenge with implementing this is that most objects are intended to be immutable, including most configurations.

However; configurations for table repairs should be possible to update in run-time (including the possibility to have different schedules for different tables). Unfortunately that is not the case at the moment. Is this the type of run-time configuration updates you are looking for?

**Comment by itskarlsson** [comment]
Closing this as it has been standing still for awhile. If this is a requirement that becomes more pressing, please feel free to reopen.
