### ISSUE TITLE
Hardcoded Cassandra version in testcontainer test cases

### ISSUE THREAD

**Issue by jwaeab** [Ericsson/ecchronos#748]
testcontainer test cases uses a hardcoded Cassandra version (4.1.5). It should use the same version as the one specified in the actions file. If none is given, default to"latest".

**Comment by VictorCavichioli** [comment]
Is it in the agent or in sidecar? Or both?

**Comment by jwaeab** [comment]
I'm not sure how/if you use testcontainer in your agent/sidecar code. In the current versions (5/6) it is hardcoded, so that is what I'm fixing.
