### ISSUE TITLE
Metrics exposed via JMX?

### ISSUE THREAD

**Issue by smiklosovic** [Ericsson/ecchronos#75]
Hi,

it would be cool if metrics were accessible via JMX so we can collect them and dashboard them e.g in Grafana via Prometheus. Is this on road map at least?

**Comment by emolsson** [comment]
Hi, thanks for the suggestion, it is now! I haven't worked with Grafana/Prometheus yet but I intend to look into it and how it can be done.

**Comment by simonfontana** [comment]
We should also look at exposing metrics (with [Prometheus support](https://prometheus.io/docs/instrumenting/exposition_formats/)) through an endpoint in the REST API now that one exists in version 2.0. Having a side-car which reads metrics through JMX just seems less elegant. Perhaps it should be a new issue though, as this one seem completed.
