### ISSUE TITLE
Integration Test for Hot Reload of Nodes

### ISSUE THREAD

**Issue by paulchandler** [Ericsson/ecchronos#757]
Story Description:

This story is to create an integration test for the Hot Reload of Nodes feature ( #699 ) 

One test should create a cluster in docker then add a node to the cluster, triggering a call to  onAdd method for class EccNodeStateListener 

Another test should create a cluster in docker then to a nodetool decommission on one of the nodes, triggering a call to  onRemove method for class EccNodeStateListener 

Acceptance Criteria:

Integrations tests written, and running green.

**Comment by VictorCavichioli** [comment]
PR merged
